// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CommonProtoBufResult.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class KeyValue;
@class Map;
@class OptMap;
@class onlyMap;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - CommonProtoBufResultRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface CommonProtoBufResultRoot : GPBRootObject
@end

#pragma mark - KeyValue

typedef GPB_ENUM(KeyValue_FieldNumber) {
  KeyValue_FieldNumber_Key = 1,
  KeyValue_FieldNumber_Value = 2,
};

@interface KeyValue : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *key;
/** Test to see if @c key has been set. */
@property(nonatomic, readwrite) BOOL hasKey;

@property(nonatomic, readwrite, copy, null_resettable) NSString *value;
/** Test to see if @c value has been set. */
@property(nonatomic, readwrite) BOOL hasValue;

@end

#pragma mark - Map

typedef GPB_ENUM(Map_FieldNumber) {
  Map_FieldNumber_ItemsArray = 1,
};

@interface Map : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<KeyValue*> *itemsArray;
/** The number of items in @c itemsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger itemsArray_Count;

@end

#pragma mark - OptMap

typedef GPB_ENUM(OptMap_FieldNumber) {
  OptMap_FieldNumber_Key = 1,
  OptMap_FieldNumber_ValueArray = 2,
};

@interface OptMap : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *key;
/** Test to see if @c key has been set. */
@property(nonatomic, readwrite) BOOL hasKey;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Map*> *valueArray;
/** The number of items in @c valueArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger valueArray_Count;

@end

#pragma mark - onlyMap

typedef GPB_ENUM(onlyMap_FieldNumber) {
  onlyMap_FieldNumber_OnlyYylistArray = 1,
};

@interface onlyMap : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OptMap*> *onlyYylistArray;
/** The number of items in @c onlyYylistArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger onlyYylistArray_Count;

@end

#pragma mark - rs

typedef GPB_ENUM(rs_FieldNumber) {
  rs_FieldNumber_InfoMap = 1,
  rs_FieldNumber_ResultListArray = 2,
  rs_FieldNumber_OptInfoMap = 3,
  rs_FieldNumber_OptResultListArray = 4,
  rs_FieldNumber_ResultCode = 5,
  rs_FieldNumber_ExtTwoRsListArray = 6,
  rs_FieldNumber_ExtThrRsListArray = 7,
  rs_FieldNumber_ExtForRsListArray = 8,
  rs_FieldNumber_ExtFiveRsListArray = 9,
  rs_FieldNumber_ExtSixRsListArray = 10,
  rs_FieldNumber_ExtSevenRsListArray = 11,
  rs_FieldNumber_ExtEightRsListArray = 12,
};

@interface rs : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Map *infoMap;
/** Test to see if @c infoMap has been set. */
@property(nonatomic, readwrite) BOOL hasInfoMap;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Map*> *resultListArray;
/** The number of items in @c resultListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger resultListArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) Map *optInfoMap;
/** Test to see if @c optInfoMap has been set. */
@property(nonatomic, readwrite) BOOL hasOptInfoMap;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<OptMap*> *optResultListArray;
/** The number of items in @c optResultListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger optResultListArray_Count;

@property(nonatomic, readwrite) int32_t resultCode;

@property(nonatomic, readwrite) BOOL hasResultCode;
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Map*> *extTwoRsListArray;
/** The number of items in @c extTwoRsListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extTwoRsListArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Map*> *extThrRsListArray;
/** The number of items in @c extThrRsListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extThrRsListArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<onlyMap*> *extForRsListArray;
/** The number of items in @c extForRsListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extForRsListArray_Count;

/** 为新增 */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Map*> *extFiveRsListArray;
/** The number of items in @c extFiveRsListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extFiveRsListArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Map*> *extSixRsListArray;
/** The number of items in @c extSixRsListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extSixRsListArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Map*> *extSevenRsListArray;
/** The number of items in @c extSevenRsListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extSevenRsListArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Map*> *extEightRsListArray;
/** The number of items in @c extEightRsListArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger extEightRsListArray_Count;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
